src/main/java/br/com/triadworks/issuetracker/model/Issue.java
package br.com.triadworks.issuetracker.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Issue implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	private String sumario;
	@Column(length=1000)
	private String descricao;
	
	@ManyToOne
	private Projeto projeto;
	
	@Enumerated(EnumType.STRING)
	private TipoDeIssue tipo;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date reportadoEm;
	
	@ManyToOne
	private Usuario reportadoPor;
	
	@ManyToOne
	private Usuario assinadoPara;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date atualizadoEm;
	
	@Enumerated(EnumType.STRING)
	private Status status = Status.ABERTA;
	
	@OneToMany(cascade=CascadeType.ALL, orphanRemoval=true, fetch=FetchType.LAZY)
	@JoinTable(name="issue_comentario", 
		joinColumns=@JoinColumn(name="issue_id"),
		inverseJoinColumns=@JoinColumn(name="comentario_id"))
	private List<Comentario> comentarios = new ArrayList<Comentario>();
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getSumario() {
		return sumario;
	}
	public void setSumario(String sumario) {
		this.sumario = sumario;
	}
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	public Projeto getProjeto() {
		return projeto;
	}
	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}
	public TipoDeIssue getTipo() {
		return tipo;
	}
	public void setTipo(TipoDeIssue tipo) {
		this.tipo = tipo;
	}
	public Date getReportadoEm() {
		return reportadoEm;
	}
	public void setReportadoEm(Date reportadoEm) {
		this.reportadoEm = reportadoEm;
	}
	public Usuario getReportadoPor() {
		return reportadoPor;
	}
	public void setReportadoPor(Usuario reportadoPor) {
		this.reportadoPor = reportadoPor;
	}
	public Usuario getAssinadoPara() {
		return assinadoPara;
	}
	public void setAssinadoPara(Usuario assinadoPara) {
		this.assinadoPara = assinadoPara;
	}
	public Date getAtualizadoEm() {
		return atualizadoEm;
	}
	public void setAtualizadoEm(Date atualizadoEm) {
		this.atualizadoEm = atualizadoEm;
	}
	public Status getStatus() {
		return status;
	}
	public void setStatus(Status status) {
		this.status = status;
	}
	public List<Comentario> getComentarios() {
		return comentarios;
	}
	public void setComentarios(List<Comentario> comentarios) {
		this.comentarios = comentarios;
	}
	
	/**
	 * Adiciona comentários à issue.
	 */
	public void comenta(Comentario comentario) {
		
		if (comentario.getAutor() == null)
			throw new IllegalArgumentException("Autor nao pode ser vazio.");
		
		comentarios.add(comentario);
	}
	/**
	 * Fecha issue com um comentário.
	 */
	public void fecha(Comentario comentario) {
		this.status = Status.FECHADA;
		this.comenta(comentario);
	}
	
	public boolean isFechada() {
		return Status.FECHADA.equals(status);
	}
	
	@PrePersist
	@PreUpdate
	public void onSaveOrUpdate() {
		this.atualizadoEm = new Date();
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Issue other = (Issue) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
}

src/main/java/br/com/triadworks/issuetracker/controller/DashboardController.java
package br.com.triadworks.issuetracker.controller;

import java.util.List;

import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Path;
import br.com.caelum.vraptor.Post;
import br.com.caelum.vraptor.Resource;
import br.com.caelum.vraptor.Result;
import br.com.triadworks.issuetracker.dao.IssueDao;
import br.com.triadworks.issuetracker.model.Comentario;
import br.com.triadworks.issuetracker.model.Issue;

@Resource
public class DashboardController {

	private final IssueDao dao;
	private final UsuarioWeb usuarioWeb;
	private final Result result;

	public DashboardController(IssueDao dao, UsuarioWeb usuarioWeb, Result result) {
		this.dao = dao;
		this.usuarioWeb = usuarioWeb;
		this.result = result;
	}
	
	@Get
	@Path("/dashboard")
	public List<Issue> dashboard() {
		result.include("todasAsIssues", dao.listaTudo());
		Long id = usuarioWeb.getUsuario().getId();
		return dao.getIssuesDoUsuario(id);
	}
	
	@Get
	@Path("/dashboard/issues/{id}")
	public Issue detalhe(Long id) {
		Issue issue = dao.carrega(id);
		return issue;
	}
	
	@Post
	@Path("/dashboard/issues/{id}/comenta")
	public void comentaIssue(Long id, Comentario comentario) {
		comentario.setAutor(usuarioWeb.getUsuario());
		dao.comenta(id, comentario);
		result.redirectTo(this).detalhe(id);
	}
	
	@Post
	@Path("/dashboard/issues/{id}/fecha")
	public void fechaIssue(Long id, Comentario comentario) {
		comentario.setAutor(usuarioWeb.getUsuario());
		dao.fecha(id, comentario);
		result.redirectTo(this).detalhe(id);
	}
	
}

src/main/webapp/WEB-INF/jsp/dashboard/dashboard.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="/templates/jstl.jsp" %>

<!DOCTYPE html>
<html>
	<head>
		<!-- Meus imports -->
	</head>
	<body>
		<div class="page-header">
			<h1>Dashboard <small>do ${usuarioWeb.usuario.nome }</small></h1>
		</div>
		
		<div class="tabbable tabs-left">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab1" data-toggle="tab">Minhas Issues</a></li>
				<li><a href="#tab2" data-toggle="tab">Todas</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<table class="table table-striped ">
						<tbody>
							<c:forEach var="issue" items="${issueList}">
								<tr>
									<td>#${issue.id }</td>
									<td>
										<strong>
											<span class="muted">${issue.projeto.nome } »</span>
											<a href="${ctx }/dashboard/issues/${issue.id }">${issue.sumario }</a>
										</strong>
										<p>
											<small>
												Aberto por <b>${issue.reportadoPor.nome }</b> em 
												<fmt:formatDate value="${issue.reportadoEm }" pattern="dd/MM/yyyy 'as' hh:mm"/>
											</small>
										</p>
									</td>
									<td>
										<c:if test="${issue.fechada}">
											<span class="label label-important">${issue.status }</span>
										</c:if>
										<c:if test="${!issue.fechada}">
											<span class="label label-success">${issue.status }</span>
										</c:if>
									</td>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</div>
				<div class="tab-pane" id="tab2">
					<table class="table table-striped ">
						<tbody>
							<c:forEach var="issue" items="${todasAsIssues}">
								<tr>
									<td>#${issue.id }</td>
									<td>
										<strong>
											<span class="muted">${issue.projeto.nome } »</span>
											<a href="${ctx }/dashboard/issues/${issue.id }">${issue.sumario }</a>
										</strong>
										<p>
											<small>
												Aberto por <b>${issue.reportadoPor.nome }</b> em 
												<fmt:formatDate value="${issue.reportadoEm }" pattern="dd/MM/yyyy 'as' hh:mm"/>
											</small>
										</p>
									</td>
									<td>
										<c:if test="${issue.fechada}">
											<span class="label label-important">${issue.status }</span>
										</c:if>
										<c:if test="${!issue.fechada}">
											<span class="label label-success">${issue.status }</span>
										</c:if>
									</td>
								</tr>
							</c:forEach>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</body>
</html>

src/main/webapp/WEB-INF/jsp/dashboard/detalhe.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ include file="/templates/jstl.jsp" %>

<!DOCTYPE html>
<html>
	<head>
		<!-- Meus imports -->
		<script type="text/javascript">
			$(function(){
				
				$("#form").validate({
					onkeyup: false,
					rules: {
						"comentario.descricao": {
							required: true,
							maxlength: 2000
						}
					},
				});
				
				/**
				 * Altera action do form antes de fechar a Issue
				 */	
				$("#btn_fecha").click(function(){
					var action = $("#form").attr("action");
					var novaAction = action.replace("comenta", "fecha");
					$("#form").attr("action", novaAction);
				});
				
			});
		</script>
	</head>
	<body>
	
		<a href="${ctx}/dashboard"><i class="icon-arrow-left"></i> Voltar ao Dashboard</a>
	
		<h2>
				#${issue.id } &nbsp; ${issue.sumario}
		</h2>
		<p>
			<div class="row">
				<div class="span1">
					<c:set var="status_class" value="${issue.fechada ? 'label-important' : 'label-success'}" />
					<span class="label ${status_class }">${issue.status }</span>
				</div>
				<div class="span8 lead">${issue.descricao }</div>
			</div>
		</p>
		
		<hr />
		
		<c:forEach var="comentario" items="${issue.comentarios }">
			<div class="media span9">
				<a class="pull-left" href="#">
					<img class="media-object" src=${ctx }/img/photo_user.png>
				</a>
				<div class="media-body">
					<h4 class="media-heading">${comentario.autor.nome} 
						<small> » <fmt:formatDate value="${comentario.criadaEm }" pattern="dd/MM/yyyy',' HH:mm "/></small>
					</h4>
					${comentario.descricao }
					<hr />
				</div>
			</div>
		</c:forEach>
		
		<c:set var="disabled" value="${issue.fechada ? 'disabled' : ''}" />
		
		<form id="form" action="${ctx }/dashboard/issues/${issue.id}/comenta" method="post">
			<div class="control-group required">
				<label class="control-label">Comente nesta issue</label>
				<div class="controls">
					<textarea rows="4" class="span9_" style="width: 99%;"
						name="comentario.descricao" ${disabled }></textarea>
				</div>
			</div>
			<div class="pull-right">
				<button id="btn_comenta" type="submit" 
					class="btn btn-success" ${disabled }><i class="icon-comment icon-white"></i> Comentar</button>
				<button id="btn_fecha" type="submit" 
					class="btn btn-danger" ${disabled }><i class="icon-check icon-white"></i> Fechar e Comentar</button>
			</div>
		</form>
		
	</body>
</html>